- hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"

  - name: List key files
    shell: (cd /root/.ssh; find . -maxdepth 1 -type f -iname '*key.pem')| cut -d'/' -f2
    register: file_to_copy
  - name: Tower Creds key file
    tower_credential:
      name: Creds for AWS instances
      organization: Default
      state: present
      kind: ssh
      tower_host: tower1.{{tower_guid}}.example.opentlc.com
      tower_username: admin
      tower_password: r3dh4t1!
      tower_verify_ssl: no
      ssh_key_data: "/root/.ssh/{{ file_to_copy.stdout }}"
      username: ec2-user
  - name: Update Prod Job template
    tower_job_template:
      name: "09_3 tier app on Prod"
      credential: "Creds for AWS instances"
      tower_host: tower1.{{tower_guid}}.example.opentlc.com
      tower_username: admin
      tower_password: r3dh4t1!
      tower_verify_ssl: no
      state: present
      job_type: run
      playbook: site-3tier-app.yml
      project: "00_Homework Assignment"
  - name: Update Prod Smoke Job template
    tower_job_template:
      name: "10_Smoke test Prod env"
      credential: "Creds for AWS instances"
      tower_host: tower1.{{tower_guid}}.example.opentlc.com
      tower_username: admin
      tower_password: r3dh4t1!
      tower_verify_ssl: no
      state: present
      job_type: run
      playbook: site-smoketest-aws.yml
      project: "00_Homework Assignment"

    
