- hosts: workstation
  gather_facts: false
  roles:
    - osp-facts

# Setup front-end load balancer tier
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - lb-tier

# Setup application servers tier
- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - base-config

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - db-tier
