---

- name: Copy HAProxy  package
  copy:
    src: haproxy-1.5.18-9.el7.x86_64.rpm
    dest: /tmp/haproxy-1.5.18-9.el7.x86_64.rpm
    mode: 0644

- name: Enable repos
  yum_repository:
    name: local_repo
    description: Organisation local YUM repo
    baseurl: http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.6.4-1/rhel-7-server-rpms

- name: Enable repos
  yum_repository:
    name: local_repo_extra
    description: Organisation local YUM repo
    baseurl: http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.6.4-1/rhel-7-server-extras-rpms
 
- name: Enable repos
  yum_repository:
    name: local_repo_extra_optional
    description: Organisation local YUM repo
    baseurl: http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.6.4-1/rhel-7-server-optional-rpms

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    disable_gpg_check: yes
  vars:
    packages:
    - haproxy

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: no

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
    notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
