---

- name: Ensure HAProxy is installed.
  package: name=haproxy state=present

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: no

- name: Copy HAProxy configuration in place.
  template:
    src: roles/lb-tier/templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
