---

- name: Copy HAProxy  package
  template:
    src: /root/nextgen_ansible_advanced_homework/roles/lb-tier/templates/haproxy-1.5.18-9.el7.x86_64.rpm
    dest: /tmp/haproxy-1.5.18-9.el7.x86_64.rpm
    mode: 0644

- name: Ensure HAProxy is installed.
  #package: name=haproxy state=present
  command: yum localinstall -y /tmp/haproxy-1.5.18-9.el7.x86_64.rpm

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: no

- name: Copy HAProxy configuration in place.
  template:
    src: /root/nextgen_ansible_advanced_homework/roles/lb-tier/templates//haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
