---

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: Enable repos
  yum_repository:
    name: local_repo
    description: Organisation local YUM repo
    baseurl: http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.6.4-1/rhel-7-server-rpms

- name: Enable repos
  yum_repository:
    name: local_repo_extra
    description: Organisation local YUM repo
    baseurl: http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.6.4-1/rhel-7-server-extras-rpms
 
- name: Enable repos
  yum_repository:
    name: local_repo_extra_optional
    description: Organisation local YUM repo
    baseurl: http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.6.4-1/rhel-7-server-optional-rpms

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    disable_gpg_check: yes
  vars:
    packages:
    - httpd
    - httpd-tools

- name: start httpd
  service:
    name: httpd
    state: started
